# Generated by Django 5.2.1 on 2025-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_bio_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='owned_avatars',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('base_1.png', 'base_1.png'), ('base_2.png', 'base_2.png'), ('base_3.png', 'base_3.png')], default='base_1.png', max_length=50),
        ),
    ]
