# Generated by Django 5.2.1 on 2025-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_coins_profile_owned_avatars_profile_points_and_more'),
        ('shops', '0002_alter_avataritem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owned_avatars',
        ),
        migrations.AddField(
            model_name='profile',
            name='owned_items',
            field=models.ManyToManyField(blank=True, to='shops.avataritem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
