# Generated by Django 5.2.1 on 2025-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_owned_avatars_profile_owned_items_and_more'),
        ('shops', '0002_alter_avataritem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owned_items',
        ),
        migrations.AddField(
            model_name='profile',
            name='owned_skins',
            field=models.ManyToManyField(blank=True, related_name='owners', to='shops.avataritem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
