# Generated by Django 5.2.1 on 2025-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_owned_items_profile_owned_skins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='mistik.jpg', max_length=100),
        ),
    ]
