# Generated by Django 5.2.1 on 2025-06-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
        ('tasks', '0005_taskanswer_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='notification',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.taskanswer'),
        ),
    ]
