# Generated by Django 5.2.1 on 2025-06-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_notification_is_accepted_notification_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='answer',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
