# Generated by Django 5.2.1 on 2025-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_notification_answer_notification_is_accepted'),
        ('shops', '0003_computeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owned_computeritems',
            field=models.ManyToManyField(blank=True, related_name='owned_computeritems', to='shops.computeritem'),
        ),
    ]
