# Generated by Django 5.2.1 on 2025-06-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_owned_computeritems'),
        ('shops', '0003_computeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='shops.computeritem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='active_skin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='shops.avataritem'),
        ),
    ]
