# Generated by Django 5.2.1 on 2025-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_avataritem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='shop_items/computer_items/')),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
