# Generated by Django 5.2.1 on 2025-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_theory_task_theory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(default=0, help_text='Сколько очков получает пользователь за выполнение этого задания'),
        ),
    ]
