# Generated by Django 5.2.1 on 2025-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanswer',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
